openapi: 3.0.3
info:
  title: API Documentation
  version: 1.0.0
  description: API documentation for the application.
servers:
  - url: http://localhost:3000/api/v1
    description: Development server
paths:
  /user:
    post:
      summary: Register a new user
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                role:
                  type: string
              required:
                - username
                - password
      responses:
        "201":
          description: User successfully created
        "400":
          description: Validation error

  /user/login:
    post:
      summary: Login user
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        "200":
          description: Login successful
        "401":
          description: Invalid credentials

  /departement:
    get:
      summary: Search departements
      tags:
        - Departement
      responses:
        "200":
          description: List of departements
    post:
      summary: Create a new departement
      tags:
        - Departement
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        "201":
          description: Departement successfully created
        "401":
          description: Unauthorized access

  /departement/{departementId}:
    get:
      summary: Get a specific departement by ID
      tags:
        - Departement
      parameters:
        - name: departementId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Departement details
        "404":
          description: Departement not found

    patch:
      summary: Update a specific departement by ID
      tags:
        - Departement
      security:
        - bearerAuth: []
      parameters:
        - name: departementId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        "200":
          description: Departement successfully updated
        "401":
          description: Unauthorized access
        "404":
          description: Departement not found

    delete:
      summary: Delete a specific departement by ID
      tags:
        - Departement
      security:
        - bearerAuth: []
      parameters:
        - name: departementId
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Departement successfully deleted
        "401":
          description: Unauthorized access
        "404":
          description: Departement not found

  /leave/draft:
    post:
      summary: Save leave request as draft
      tags:
        - Leave
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reason:
                  type: string
                startDate:
                  type: string
                  format: date
                endDate:
                  type: string
                  format: date
              required:
                - reason
                - startDate
                - endDate
      responses:
        "201":
          description: Leave request saved as draft
        "401":
          description: Unauthorized access

  /leave/{leaveId}/submit:
    put:
      summary: Submit a leave request
      tags:
        - Leave
      security:
        - bearerAuth: []
      parameters:
        - name: leaveId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Leave request submitted
        "401":
          description: Unauthorized access
        "404":
          description: Leave request not found

  /leave/{leaveId}/verify:
    put:
      summary: Verify a leave request
      tags:
        - Leave
      security:
        - bearerAuth: []
      parameters:
        - name: leaveId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Leave request verified
        "401":
          description: Unauthorized access
        "404":
          description: Leave request not found

  /leave/{leaveId}/update:
    put:
      summary: Update a leave draft
      tags:
        - Leave
      security:
        - bearerAuth: []
      parameters:
        - name: leaveId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Leave draft updated
        "401":
          description: Unauthorized access
        "404":
          description: Leave draft not found

  /leave/{leaveId}:
    delete:
      summary: Remove a leave draft
      tags:
        - Leave
      security:
        - bearerAuth: []
      parameters:
        - name: leaveId
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Leave draft deleted
        "401":
          description: Unauthorized access
        "404":
          description: Leave draft not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
